# Generated by Django 6.0.5 on 2026-05-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('article_text', models.TextField(blank=True, default='')),
                ('score', models.IntegerField()),
                ('result_label', models.CharField(max_length=20)),
                ('matched_keywords', models.TextField(default='{}')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
