# Generated by Django 6.0.5 on 2026-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanalysis',
            name='article_text',
            field=models.TextField(),
        ),
    ]
