# Generated by Django 6.0.5 on 2026-05-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_newsanalysis_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanalysis',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
